"""
Git Commit Agent.

Handles branch creation and file commits to GitHub.
"""

import time
from datetime import datetime
import structlog

from src.models.state import AgentState, GitOperation
from src.integrations.github_client import GitHubClient

logger = structlog.get_logger()


class GitCommitAgent:
    """Creates branches and commits workflow files."""
    
    def __init__(self, github_client: GitHubClient, branch_prefix: str = "agent/ci-"):
        """
        Initialize commit agent.
        
        Args:
            github_client: GitHub API client
            branch_prefix: Prefix for generated branch names
        """
        self.github_client = github_client
        self.branch_prefix = branch_prefix
    
    def commit(self, state: AgentState) -> AgentState:
        """
        Create branch and commit workflow file.
        
        Args:
            state: Current state with workflow_content
        
        Returns:
            Updated state with git_operation
        """
        if not state.workflow_content:
            state.add_error("Cannot commit without workflow content")
            state.next_action = "fail"
            return state
        
        logger.info(
            "committing_workflow",
            repo=f"{state.repo_owner}/{state.repo_name}",
        )
        
        start_time = time.time()
        
        try:
            repo = self.github_client.get_repository(state.repo_owner, state.repo_name)
            
            # Generate branch name with timestamp
            timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
            branch_name = f"{self.branch_prefix}{timestamp}"
            
            # Create branch
            logger.info("creating_branch", branch=branch_name, base=state.repo_branch)
            base_sha = self.github_client.create_branch(
                repo=repo,
                branch_name=branch_name,
                source_branch=state.repo_branch,
            )
            
            # Commit workflow file
            logger.info("committing_file", path=state.workflow_content.path)
            commit_sha = self.github_client.commit_file(
                repo=repo,
                path=state.workflow_content.path,
                content=state.workflow_content.content,
                message=self._generate_commit_message(state),
                branch=branch_name,
            )
            
            # Create git operation record
            git_operation = GitOperation(
                branch_name=branch_name,
                commit_sha=commit_sha,
                commit_message=self._generate_commit_message(state),
            )
            
            state.git_operation = git_operation
            state.next_action = "create_pr"
            
            duration = time.time() - start_time
            state.add_agent_record(
                agent_name="GitCommit",
                action="commit",
                result=f"Branch: {branch_name}, SHA: {commit_sha[:8]}",
                duration=duration,
            )
            
            logger.info(
                "commit_complete",
                branch=branch_name,
                commit_sha=commit_sha[:8],
                duration=duration,
            )
            
            return state
            
        except Exception as e:
            error_msg = f"Git commit failed: {str(e)}"
            logger.error("commit_failed", error=str(e))
            state.add_error(error_msg)
            state.next_action = "fail"
            return state
    
    def _generate_commit_message(self, state: AgentState) -> str:
        """
        Generate descriptive commit message.
        
        Args:
            state: Current state
        
        Returns:
            Commit message string
        """
        language = state.repo_metadata.language if state.repo_metadata else "unknown"
        
        message_lines = [
            f"feat: Add CI workflow for {language} project",
            "",
            "Generated by Agentic CI Orchestrator",
            "",
            f"- Language: {language}",
        ]
        
        if state.repo_metadata:
            if state.repo_metadata.package_manager:
                message_lines.append(f"- Package Manager: {state.repo_metadata.package_manager}")
            if state.repo_metadata.has_tests:
                message_lines.append(f"- Tests: Included")
            if state.repo_metadata.has_linter:
                message_lines.append(f"- Linting: Enabled")
        
        if state.workflow_content:
            message_lines.append(f"- Confidence: {state.workflow_content.confidence:.0%}")
        
        return "\n".join(message_lines)
